spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: liyixin23
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT配置
jwt:
  secret: aufp8ciqNM6zsVGE1D0IAUwxmPndQXge
  expiration: 86400000 # token有效期，单位毫秒，这里设置为24小时
  refreshExpiration: 604800000 # 刷新token有效期，单位毫秒，这里设置为7天
  header: Authorization # HTTP请求头中的token字段
  token-prefix: "Bearer " # token前缀

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.uptra.schoolwork.modules.*.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    cn.uptra.schoolwork: debug

# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /
